# ===============================
# Configuration for aws environment to enable SSL (https)
# ===============================
server.port=443
server.ssl.key-store=${SSL_HOME}/mysslkeystore.p12
server.ssl.key-store-password=anup123
server.ssl.keyStoreType=PKCS12
server.ssl.keyAlias=mysslcert

# ===============================
# MySQL Database connection details for aws environment databases
# ===============================
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://mysqlawstestdb.cc3auwwyy8z2.us-east-1.rds.amazonaws.com:3306/testdbaws
spring.datasource.url=jdbc:mysql://mysqlawstestdb.cc3auwwyy8z2.us-east-1.rds.amazonaws.com:3306/testdbaws
spring.datasource.username=admin
spring.datasource.password=admin12334

