spring.application.name=demo
server.servlet.context-path=/demo
spring.profile.active=test

#server.port=443
server.ssl.key-store=C:/SWDTOOLS/ssl/mysslkeystore.p12
server.ssl.key-store-password=anup123
server.ssl.keyStoreType=PKCS12
server.ssl.keyAlias=mysslcert

